# Helix Editor Configuration
# Documentation: https://docs.helix-editor.com/configuration.html

theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
auto-pairs = true
auto-completion = true
auto-format = true
idle-timeout = 4000
completion-trigger-len = 2
preview-completion-insert = true
color-modes = false
scrolloff = 5
scroll-lines = 3
shell = ["zsh", "-c"]
text-width = 120
bufferline = "always"
true-color = true
undercurl = true
rulers = [80, 120]
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "󰰛 NORMAL"
mode.insert = "󰰝 INSERT" 
mode.select = "󰰟 SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
goto-reference-include-declaration = true
snippets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.search]
smart-case = true
wrap-around = true

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 40
wrap-indicator = "↪ "

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[keys.normal]
# Quick commands
";" = "command_mode"
":" = "command_mode"

# File operations
"C-s" = ":w"
"C-o" = "file_picker"

# Multi-cursor support
"C-d" = "select_next_sibling"
"C-D" = "select_all_siblings"
"A-d" = "select_all_children"

# Smart selection (tree-sitter powered)
"A-p" = "select_prev_sibling"
"A-n" = "select_next_sibling"
"A-i" = "select_all_siblings"
"A-a" = "select_all_children"

# Buffer management
"C-b" = "buffer_picker"
"C-p" = "file_picker"

# Navigation
"C-h" = "jump_view_left"
"C-j" = "jump_view_down" 
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

# Terminal
"C-t" = ":sh $SHELL"

# Window management
"C-w" = { h = "jump_view_left", j = "jump_view_down", k = "jump_view_up", l = "jump_view_right" }

# Alternative keybindings for common actions
"A-f" = "file_picker_in_current_buffer_directory"

[keys.insert]
# Save in insert mode
"C-s" = ["normal_mode", ":w", "insert_mode"]

[keys.select]
# Save in select mode
"C-s" = ["normal_mode", ":w"]